---
# Configures labels to be automatically applied to PRs based on paths.
#
# See: https://github.com/actions/labeler

10.x:
    - maintenance/projects/js-themes-toolkit/*
    - maintenance/projects/js-themes-toolkit/**/*

2.x:
    - maintenance/projects/js-toolkit-v2-x/*
    - maintenance/projects/js-toolkit-v2-x/**/*

3.x:
    - maintenance/projects/js-toolkit/*
    - maintenance/projects/js-toolkit/**/*

8.x:
    - maintenance/projects/js-themes-toolkit-v8-x/*
    - maintenance/projects/js-themes-toolkit-v8-x/**/*

9.x:
    - maintenance/projects/js-themes-toolkit-v9-x/*
    - maintenance/projects/js-themes-toolkit-v9-x/**/*

amd-loader:
    - maintenance/projects/amd-loader/*
    - maintenance/projects/amd-loader/**/*

changelog-generator:
    - projects/npm-tools/packages/changelog-generator/*
    - projects/npm-tools/packages/changelog-generator/**/*

docs:
    - '*.md'
    - '**/*.md'

eslint-plugin:
    - projects/eslint-plugin/*
    - projects/eslint-plugin/**/*

guidelines:
    - guidelines/*
    - guidelines/**/*

jest-junit-reporter:
    - projects/npm-tools/packages/jest-junit-reporter/*
    - projects/npm-tools/packages/jest-junit-reporter/**/*

jquery-form:
    - third-party/projects/jquery-form/*
    - third-party/projects/jquery-form/**/*

js-insights:
    - projects/npm-tools/packages/js-insights/*
    - projects/npm-tools/packages/js-insights/**/*

js-publish:
    - projects/npm-tools/packages/js-publish/*
    - projects/npm-tools/packages/js-publish/**/*

js-themes-toolkit:
    - projects/js-themes-toolkit/*
    - projects/js-themes-toolkit/**/*
    - maintenance/projects/js-themes-toolkit-v8-x/*
    - maintenance/projects/js-themes-toolkit-v8-x/**/*
    - maintenance/projects/js-themes-toolkit-v9-x/*
    - maintenance/projects/js-themes-toolkit-v9-x/**/*

js-toolkit:
    - maintenance/projects/js-toolkit/*
    - maintenance/projects/js-toolkit/**/*

npm-bundler-preset-liferay-dev:
    - projects/npm-tools/packages/npm-bundler-preset-liferay-dev/*
    - projects/npm-tools/packages/npm-bundler-preset-liferay-dev/**/*

npm-scripts:
    - projects/npm-tools/packages/npm-scripts/*
    - projects/npm-tools/packages/npm-scripts/**/*

npm-tools:
    - projects/npm-tools/*
    - projects/npm-tools/**/*

senna:
    - maintenance/projects/senna/*
    - maintenance/projects/senna/**/*
